<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'id' => 1,
                'category_id' => 1, // Clothing
                'name' => 'Casual T-Shirt',
                'code' => 'TSHIRT001',
                'size' => 'M',
                'color' => 'Blue',
                'price' => 150000.00,
                'stock' => 50,
                'description' => 'Comfortable cotton t-shirt',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'category_id' => 2, // Accessories
                'name' => 'Leather Belt',
                'code' => 'BELT001',
                'size' => 'L',
                'color' => 'Black',
                'price' => 75000.00,
                'stock' => 30,
                'description' => 'Genuine leather belt',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'category_id' => 3, // Footwear
                'name' => 'Running Shoes',
                'code' => 'SHOES001',
                'size' => '42',
                'color' => 'White',
                'price' => 300000.00,
                'stock' => 20,
                'description' => 'Lightweight running shoes',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'category_id' => 1, // Clothing
                'name' => 'Formal Shirt',
                'code' => 'SHIRT001',
                'size' => 'L',
                'color' => 'White',
                'price' => 200000.00,
                'stock' => 25,
                'description' => 'Classic formal shirt perfect for office wear',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'category_id' => 2, // Accessories
                'name' => 'Wool Scarf',
                'code' => 'SCARF001',
                'size' => '-',
                'color' => 'Red',
                'price' => 50000.00,
                'stock' => 40,
                'description' => 'Warm and cozy wool scarf',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'category_id' => 3, // Footwear
                'name' => 'Leather Boots',
                'code' => 'BOOTS001',
                'size' => '43',
                'color' => 'Brown',
                'price' => 450000.00,
                'stock' => 15,
                'description' => 'Durable leather boots for all seasons',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'category_id' => 1,
                'name' => 'Summer Dress',
                'code' => 'DRESS001',
                'size' => 'S',
                'color' => 'Yellow',
                'price' => 180000.00,
                'stock' => 20,
                'description' => 'Lightweight summer dress with floral patterns',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'category_id' => 2,
                'name' => 'Sunglasses',
                'code' => 'GLASSES001',
                'size' => '-',
                'color' => 'Black',
                'price' => 120000.00,
                'stock' => 35,
                'description' => 'Stylish UV-protected sunglasses',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'category_id' => 3,
                'name' => 'Casual Sneakers',
                'code' => 'SNEAKERS001',
                'size' => '41',
                'color' => 'Grey',
                'price' => 275000.00,
                'stock' => 22,
                'description' => 'Comfortable sneakers for daily wear',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'category_id' => 1,
                'name' => 'Hoodie Jacket',
                'code' => 'HOODIE001',
                'size' => 'XL',
                'color' => 'Navy',
                'price' => 230000.00,
                'stock' => 18,
                'description' => 'Cozy hoodie jacket with front pockets',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'category_id' => 2,
                'name' => 'Canvas Backpack',
                'code' => 'BAG001',
                'size' => '-',
                'color' => 'Khaki',
                'price' => 175000.00,
                'stock' => 20,
                'description' => 'Durable canvas backpack with spacious compartments',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'category_id' => 3,
                'name' => 'Flip Flops',
                'code' => 'FLIP001',
                'size' => '40',
                'color' => 'Blue',
                'price' => 50000.00,
                'stock' => 50,
                'description' => 'Simple and comfortable flip flops',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'category_id' => 1,
                'name' => 'Slim Fit Jeans',
                'code' => 'JEANS001',
                'size' => '32',
                'color' => 'Dark Blue',
                'price' => 250000.00,
                'stock' => 27,
                'description' => 'Stylish slim fit denim jeans',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'category_id' => 2,
                'name' => 'Wristwatch',
                'code' => 'WATCH001',
                'size' => '-',
                'color' => 'Silver',
                'price' => 300000.00,
                'stock' => 12,
                'description' => 'Elegant stainless steel wristwatch',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'category_id' => 3,
                'name' => 'Formal Shoes',
                'code' => 'FORMAL001',
                'size' => '43',
                'color' => 'Black',
                'price' => 400000.00,
                'stock' => 14,
                'description' => 'Polished leather formal shoes',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'category_id' => 1,
                'name' => 'Casual Shorts',
                'code' => 'SHORTS001',
                'size' => 'L',
                'color' => 'Beige',
                'price' => 100000.00,
                'stock' => 30,
                'description' => 'Breathable casual shorts for summer',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'category_id' => 2,
                'name' => 'Knitted Hat',
                'code' => 'HAT001',
                'size' => '-',
                'color' => 'Grey',
                'price' => 40000.00,
                'stock' => 45,
                'description' => 'Soft and warm knitted hat',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'category_id' => 3,
                'name' => 'Sports Sandals',
                'code' => 'SANDALS001',
                'size' => '42',
                'color' => 'Black',
                'price' => 125000.00,
                'stock' => 26,
                'description' => 'Comfortable and lightweight sports sandals',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'category_id' => 1,
                'name' => 'Polo Shirt',
                'code' => 'POLO001',
                'size' => 'M',
                'color' => 'Green',
                'price' => 160000.00,
                'stock' => 24,
                'description' => 'Classic cotton polo shirt',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'category_id' => 2,
                'name' => 'Leather Wallet',
                'code' => 'WALLET001',
                'size' => '-',
                'color' => 'Brown',
                'price' => 90000.00,
                'stock' => 33,
                'description' => 'Premium genuine leather wallet',
                'image' => '/assets/images/product-example.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
